# -*- coding: utf-8 -*-
"""intrusion_detection_system_(6).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TJ2BwzSMQy91v49PUetRLP61TdTj3NIt

<a id="1"></a> <br>
# Loading

cell 1
"""

#loading and importing data
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split,StratifiedKFold,GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier,VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import make_scorer, roc_auc_score
import scipy
from scipy import stats
from sklearn.metrics import classification_report, confusion_matrix
import warnings
warnings.filterwarnings("ignore")
from sklearn.preprocessing import StandardScaler

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# add the column labels
columns = (['duration'
,'protocol_type'
,'service'
,'flag'
,'src_bytes'
,'dst_bytes'
,'land'
,'wrong_fragment'
,'urgent'
,'hot'
,'num_failed_logins'
,'logged_in'
,'num_compromised'
,'root_shell'
,'su_attempted'
,'num_root'
,'num_file_creations'
,'num_shells'
,'num_access_files'
,'num_outbound_cmds'
,'is_host_login'
,'is_guest_login'
,'count'
,'srv_count'
,'serror_rate'
,'srv_serror_rate'
,'rerror_rate'
,'srv_rerror_rate'
,'same_srv_rate'
,'diff_srv_rate'
,'srv_diff_host_rate'
,'dst_host_count'
,'dst_host_srv_count'
,'dst_host_same_srv_rate'
,'dst_host_diff_srv_rate'
,'dst_host_same_src_port_rate'
,'dst_host_srv_diff_host_rate'
,'dst_host_serror_rate'
,'dst_host_srv_serror_rate'
,'dst_host_rerror_rate'
,'dst_host_srv_rerror_rate'
,'attack'
,'level'])


df_train=pd.read_csv('/content/KDDTrain+.txt',header=None,names=columns)
df_test=pd.read_csv('/content/KDDTest+.txt',header=None,names=columns)

"""cell 2"""

df_train

"""cell 3"""

# information of our data
df_train.info()

"""cell 4"""

df_train.describe().style.background_gradient(cmap='Blues').set_properties(**{'font-family':'Segoe UI'})

"""cell 5"""

df_test.describe().style.background_gradient(cmap='Greens').set_properties(**{'font-family':'Segoe UI'})

"""<a id="2"></a> <br>
# Check for duplicates

cell 6
"""

print(df_train.duplicated().sum())
print(df_test.duplicated().sum())

"""cell 7"""

# Check for nissing data
df_train.isnull().sum()

"""<a id="3"></a> <br>
# checking for outliers

cell 8
"""

#Boxplot of all columns to see outliers
df_train.plot(kind='box', subplots=True, layout=(15, 3), figsize=(20, 40))
plt.show()

"""cell 9"""

df_train['attack'].value_counts()

"""cell 10"""

# I will convert other abnormal classes to one class

df_train["binary_attack"]=df_train.attack.map(lambda a: "normal" if a == 'normal' else "abnormal")
df_train.drop('attack',axis=1,inplace=True)

df_test["binary_attack"]=df_test.attack.map(lambda a: "normal" if a == 'normal' else "abnormal")
df_test.drop('attack',axis=1,inplace=True)

"""cell 11"""

def pie_plot(df, cols_list, rows, cols):
    fig, axes = plt.subplots(rows, cols)
    for ax, col in zip(axes.ravel(), cols_list):
        df[col].value_counts().plot(ax=ax, kind='pie', figsize=(15, 15), fontsize=10, autopct='%1.0f%%')
        ax.set_title(str(col), fontsize = 12)
    plt.show()

"""cell 12"""

pie_plot(df_train, ['protocol_type', 'binary_attack'], 1, 2)

"""cell 13"""

df_train.select_dtypes(['object']).columns

"""<a id="4"></a> <br>
# Encoding

cell 14
"""

# Label Encoder
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
clm=['protocol_type', 'service', 'flag', 'binary_attack']
for x in clm:
    df_train[x]=le.fit_transform(df_train[x])
    df_test[x]=le.fit_transform(df_test[x])

"""cell 15

<a id="5"></a> <br>
# Spliting
"""

#Spliting the data

x_train=df_train.drop('binary_attack',axis=1)
y_train=df_train["binary_attack"]

x_test=df_test.drop('binary_attack',axis=1)
y_test=df_test["binary_attack"]

"""cell 16

<a id="6"></a> <br>
# Feature Engineering
"""

from sklearn.feature_selection import mutual_info_classif
mutual_info = mutual_info_classif(x_train, y_train)
mutual_info = pd.Series(mutual_info)
mutual_info.index = x_train.columns
mutual_info.sort_values(ascending=False)

"""mutual_info_classif(x_train, y_train): This function from sklearn.feature_selection computes the mutual information for each feature in x_train with respect to the target variable y_train. Mutual information measures how much knowing the value of a feature reduces uncertainty about the target variable. It helps quantify the relevance of each feature for the classification task.

Convert to a pandas Series (pd.Series(mutual_info)): This converts the array of mutual information scores into a pandas Series for easier manipulation, such as sorting and indexing.

Assign feature names as index (mutual_info.index = x_train.columns): This assigns the column names (the feature names in x_train) as the index of the mutual information Series, allowing you to associate the mutual information score with the corresponding feature.

Sort the mutual information values in descending order (mutual_info.sort_values(ascending=False)): Sorting the mutual information values in descending order helps identify the most important features. The higher the mutual information score, the more informative the feature is for predicting the target variable.

cell 17
"""

mutual_info.sort_values(ascending=False).plot.bar(figsize=(20, 8));

"""cell 18"""

# I will choose 20 features to select
from sklearn.feature_selection import SelectKBest
sel_five_cols = SelectKBest(mutual_info_classif, k=20)
sel_five_cols.fit(x_train, y_train)
x_train.columns[sel_five_cols.get_support()]

"""SelectKBest(mutual_info_classif, k=20): This selects the top 20 features based on mutual information with the target variable.

.fit(x_train, y_train): This method fits the feature selector to the training data, computing the mutual information between each feature and the target variable.

.get_support(): This method returns a boolean mask where True values indicate the selected features. Applying this mask to x_train.columns gives you the names of the top 20 selected features.

cell 19
"""

col=['service', 'flag', 'src_bytes', 'dst_bytes', 'logged_in', 'count',
       'serror_rate', 'srv_serror_rate', 'same_srv_rate', 'diff_srv_rate',
       'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count',
       'dst_host_same_srv_rate', 'dst_host_diff_srv_rate',
       'dst_host_same_src_port_rate', 'dst_host_srv_diff_host_rate',
       'dst_host_serror_rate', 'dst_host_srv_serror_rate', 'level']
x_train=x_train[col]
x_test=x_test[col]

"""cell 20"""

plt.figure(figsize=(14,14))
p=sns.heatmap(x_train.corr(), annot=True,cmap ='RdYlGn')
plt.show()

"""cell 21"""

# Create correlation matrix
corr_matrix = x_train.corr().abs()
corr_matrix

"""cell 22"""

# Select upper triangle of correlation matrix
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

"""cell 23"""

# Find features with correlation greater than 0.95
to_drop = [column for column in upper.columns if any(upper[column] > 0.95)]
to_drop

"""cell 24"""

# Drop features
x_train.drop(to_drop, axis=1, inplace=True)

"""cell 25"""

x_test.drop(to_drop, axis=1, inplace=True)

"""cell 26"""

x_train.shape

"""<a id="7"></a> <br>
# Scaling

cell 27
"""

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_train= scaler.fit_transform(x_train)
x_test= scaler.fit_transform(x_test)

"""<a id="8"></a> <br>
# Binary classification models

cell 28
"""

# we'll initialize each model and store it by name in a dictionary
models = {}

# Logistic Regression
from sklearn.linear_model import LogisticRegression
models['Logistic Regression'] = LogisticRegression()

# Support Vector Machines
from sklearn.svm import LinearSVC
models['Support Vector Machines linear'] = LinearSVC()
models['Support Vector Machines plonomial'] = SVC(kernel='poly')
models['Support Vector Machines RBf'] =  SVC(C=100.0)

# Decision Trees
from sklearn.tree import DecisionTreeClassifier
models['Decision Trees'] = DecisionTreeClassifier(max_depth=3)

# Random Forest
from sklearn.ensemble import RandomForestClassifier
models['Random Forest'] = RandomForestClassifier()

# Naive Bayes
from sklearn.naive_bayes import GaussianNB
models['Naive Bayes'] = GaussianNB()

# K-Nearest Neighbors
from sklearn.neighbors import KNeighborsClassifier
models['K-Nearest Neighbor'] = KNeighborsClassifier(n_neighbors=20)

"""cell 29"""

# we'll loop over each one, train it by calling .fit(), make predictions, calculate metrics, and store each result in a dictionary.

from sklearn.metrics import accuracy_score, precision_score, recall_score, ConfusionMatrixDisplay

accuracy, precision, recall = {}, {}, {}

for key in models.keys():

    # Fit the classifier
    models[key].fit(x_train, y_train)

    # Make predictions
    predictions = models[key].predict(x_test)

    # Calculate metrics
    accuracy[key] = accuracy_score(predictions, y_test)
    precision[key] = precision_score(predictions, y_test)
    recall[key] = recall_score(predictions, y_test)

      # Plot confusion matrix
    disp = ConfusionMatrixDisplay.from_estimator(models[key], x_test, y_test,display_labels = ['Normal', 'Attack'])
    plt.title(f'Confusion Matrix for {key}')
    plt.show()

"""cell 30"""

df_model = pd.DataFrame(index=models.keys(), columns=['Accuracy', 'Precision', 'Recall'])
df_model['Accuracy'] = accuracy.values()
df_model['Precision'] = precision.values()
df_model['Recall'] = recall.values()

df_model

"""cell 31"""

ax = df_model.plot.barh()
ax.legend(
    ncol=len(models.keys()),
    bbox_to_anchor=(0, 1),
    loc='lower left',
    prop={'size': 14}
)
plt.tight_layout()

"""cell 32"""

from sklearn.metrics import RocCurveDisplay
for key in models.keys():
    RocCurveDisplay.from_estimator(models[key], x_test, y_test)

"""cell 33

### As we can see Randon forest and Decision tree classifiers are the best calssifiers for our data
"""

# For LSTM, we'll assume each sample is treated as one timestep
x_train_lstm = np.reshape(x_train, (x_train.shape[0], 1, x_train.shape[1]))
x_test_lstm = np.reshape(x_test, (x_test.shape[0], 1, x_test.shape[1]))

# Step 1: Define LSTM model
lstm_model = Sequential()

# LSTM layer
lstm_model.add(LSTM(units=128, input_shape=(x_train_lstm.shape[1], x_train_lstm.shape[2])))

lstm_model.add(Dropout(0.2))

# Dense layers
lstm_model.add(Dense(64, activation='relu'))
lstm_model.add(Dropout(0.3))

# Output layer
lstm_model.add(Dense(1, activation='sigmoid'))  # Use 'softmax' if you have more than 2 classes

# Step 2: Compile the model
lstm_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Step 3: Train the model
history = lstm_model.fit(x_train_lstm, y_train, epochs=50, batch_size=64, validation_split=0.1)

# Step 4: Evaluate the model
test_loss, test_acc = lstm_model.evaluate(x_test_lstm, y_test)
print(f'Test accuracy: {test_acc}')

# Assuming your trained model is named 'model'
lstm_model.save('lstm_model.h5')  # Save the model to an HDF5 file

print("Model saved successfully.")

"""cell 34"""

y_pred = lstm_model.predict(x_test_lstm)
y_pred_class = (y_pred > 0.5).astype(int)

# Precision, Recall, F1-Score, Confusion Matrix

# Calculate precision and recall
precision = precision_score(y_test, y_pred_class)
recall = recall_score(y_test, y_pred_class)

print(f'Precision: {precision}')
print(f'Recall: {recall}')
print("Classification Report:")
print(classification_report(y_test, y_pred_class))

print("Confusion Matrix:")
cm=confusion_matrix(y_test, y_pred_class)
 # Plot the confusion matrix using seaborn heatmap
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
               xticklabels=["Predicted Normal", "Predicted Attack"],
                yticklabels=["Actual Normal", "Actual Attack"])
plt.title('Confusion Matrix')
plt.ylabel('Actual Class')
plt.xlabel('Predicted Class')
plt.show()

"""Deep Learning

cell 35
"""

# Step 1: Define the neural network model
model = Sequential()

# Input layer + 1st hidden layer
model.add(Dense(128, input_dim=x_train.shape[1], activation='relu'))
model.add(Dropout(0.2))

# 2nd hidden layer
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.2))

# Output layer
model.add(Dense(1, activation='sigmoid'))  # Use 'softmax' for multi-class classification

# Step 2: Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Step 3: Train the model
history = model.fit(x_train, y_train, epochs=50, batch_size=64, validation_split=0.1)

# Step 4: Evaluate the model
test_loss, test_acc = model.evaluate(x_test, y_test)
print(f'Test accuracy: {test_acc}')

"""cell36"""

y_pred = model.predict(x_test)
y_pred_class = (y_pred > 0.5).astype(int)

# Precision, Recall, F1-Score, Confusion Matrix

# Calculate precision and recall
precision = precision_score(y_test, y_pred_class)
recall = recall_score(y_test, y_pred_class)

print(f'Precision: {precision}')
print(f'Recall: {recall}')
print("Classification Report:")
print(classification_report(y_test, y_pred_class))

print("Confusion Matrix:")
cm=confusion_matrix(y_test, y_pred_class)
 # Plot the confusion matrix using seaborn heatmap
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
               xticklabels=["Predicted Normal", "Predicted Attack"],
                yticklabels=["Actual Normal", "Actual Attack"])
plt.title('Confusion Matrix')
plt.ylabel('Actual Class')
plt.xlabel('Predicted Class')
plt.show()

"""cell 37"""

lstm_model.summary()

"""cell 38"""

import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'], label='train_accuracy')
plt.plot(history.history['val_accuracy'], label='val_accuracy')
plt.title('Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend()
plt.show()

plt.plot(history.history['loss'], label='train_loss')
plt.plot(history.history['val_loss'], label='val_loss')
plt.title('Model Loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend()
plt.show()

"""Predictions

cell39
"""

import pandas as pd
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler

# List of all columns (as provided)
columns = ['duration', 'protocol_type', 'service', 'flag', 'src_bytes', 'dst_bytes',
           'land', 'wrong_fragment', 'urgent', 'hot', 'num_failed_logins', 'logged_in',
           'num_compromised', 'root_shell', 'su_attempted', 'num_root', 'num_file_creations',
           'num_shells', 'num_access_files', 'num_outbound_cmds', 'is_host_login',
           'is_guest_login', 'count', 'srv_count', 'serror_rate', 'srv_serror_rate',
           'rerror_rate', 'srv_rerror_rate', 'same_srv_rate', 'diff_srv_rate',
           'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count',
           'dst_host_same_srv_rate', 'dst_host_diff_srv_rate',
           'dst_host_same_src_port_rate', 'dst_host_srv_diff_host_rate',
           'dst_host_serror_rate', 'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
           'dst_host_srv_rerror_rate', 'attack', 'level']

# Raw data (as provided)
raw_data = [0,'tcp','private','S0',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,203,14,1.00,1.00,0.00,0.00,0.07,0.06,0.00,255,14,0.05,0.07,0.00,0.00,1.00,1.00,0.00,0.00,'neptune',21]
# Create a DataFrame using the columns and raw data
df = pd.DataFrame([raw_data], columns=columns)

# Columns to select
selected_columns = ['service', 'flag', 'src_bytes', 'dst_bytes', 'logged_in', 'count',
                    'serror_rate', 'same_srv_rate', 'diff_srv_rate',
                    'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count',
                    'dst_host_same_srv_rate', 'dst_host_diff_srv_rate',
                    'dst_host_same_src_port_rate', 'dst_host_srv_diff_host_rate', 'level']

# Select only the specified columns
df_selected = df[selected_columns]

# Drop the specified columns
columns_to_drop = ['srv_serror_rate', 'dst_host_serror_rate', 'dst_host_srv_serror_rate']
df_selected = df_selected.drop(columns=columns_to_drop, errors='ignore')

# Label encode the selected columns that are of object type
le = preprocessing.LabelEncoder()
for column in df_selected.select_dtypes(include=['object']).columns:
    df_selected[column] = le.fit_transform(df_selected[column])

# Initialize the MinMaxScaler
# scaler = MinMaxScaler()

# # Scale the numerical columns
# numerical_columns = df_selected.select_dtypes(include=['int64', 'float64']).columns
# df_selected[numerical_columns] = scaler.fit_transform(df_selected[numerical_columns])

# Show the resulting DataFrame after scaling
print(df_selected)

# Prepare the input for LSTM
x_input_lstm = np.reshape(df_selected.values, (df_selected.shape[0], 1, df_selected.shape[1]))  # Reshape for LSTM

"""cell 40"""

from tensorflow.keras.models import load_model

# Load the trained LSTM model
lstm_model = load_model('lstm_model.h5')

"""cell 41"""

# Make predictions
predictions = lstm_model.predict(x_input_lstm)
print(predictions)
# If binary classification, convert probabilities to class labels
predicted_classes = (predictions > 0.5).astype(int)  # Adjust the threshold as necessary
# Map 0 and 1 to 'normal' and 'abnormal'
predicted_labels = ['Anomly' if pred == 0 else 'Normal' for pred in predicted_classes.flatten()]

# Display the predictions
print("Predicted class:", predicted_labels)

"""cell 42"""

import pandas as pd
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler

# List of all columns (as provided)
columns = ['duration', 'protocol_type', 'service', 'flag', 'src_bytes', 'dst_bytes',
           'land', 'wrong_fragment', 'urgent', 'hot', 'num_failed_logins', 'logged_in',
           'num_compromised', 'root_shell', 'su_attempted', 'num_root', 'num_file_creations',
           'num_shells', 'num_access_files', 'num_outbound_cmds', 'is_host_login',
           'is_guest_login', 'count', 'srv_count', 'serror_rate', 'srv_serror_rate',
           'rerror_rate', 'srv_rerror_rate', 'same_srv_rate', 'diff_srv_rate',
           'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count',
           'dst_host_same_srv_rate', 'dst_host_diff_srv_rate',
           'dst_host_same_src_port_rate', 'dst_host_srv_diff_host_rate',
           'dst_host_serror_rate', 'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
           'dst_host_srv_rerror_rate', 'attack', 'level']

# Raw data (as provided)
raw_data = [0,'tcp','http','SF',283,3160,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,26,26,0.00,0.00,0.00,0.00,1.00,0.00,0.00,255,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,'normal',21]
# Create a DataFrame using the columns and raw data
df = pd.DataFrame([raw_data], columns=columns)

# Columns to select
selected_columns = ['service', 'flag', 'src_bytes', 'dst_bytes', 'logged_in', 'count',
                    'serror_rate', 'same_srv_rate', 'diff_srv_rate',
                    'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count',
                    'dst_host_same_srv_rate', 'dst_host_diff_srv_rate',
                    'dst_host_same_src_port_rate', 'dst_host_srv_diff_host_rate', 'level']

# Select only the specified columns
df_selected = df[selected_columns]

# Drop the specified columns
columns_to_drop = ['srv_serror_rate', 'dst_host_serror_rate', 'dst_host_srv_serror_rate']
df_selected = df_selected.drop(columns=columns_to_drop, errors='ignore')

# Label encode the selected columns that are of object type
le = preprocessing.LabelEncoder()
for column in df_selected.select_dtypes(include=['object']).columns:
    df_selected[column] = le.fit_transform(df_selected[column])

# Initialize the MinMaxScaler
# scaler = MinMaxScaler()

# # Scale the numerical columns
# numerical_columns = df_selected.select_dtypes(include=['int64', 'float64']).columns
# df_selected[numerical_columns] = scaler.fit_transform(df_selected[numerical_columns])

# Show the resulting DataFrame after scaling
print(df_selected)

# Prepare the input for LSTM
x_input_lstm = np.reshape(df_selected.values, (df_selected.shape[0], 1, df_selected.shape[1]))  # Reshape for LSTM

"""cell 43"""

# Make predictions
predictions = lstm_model.predict(x_input_lstm)
print(predictions)
# If binary classification, convert probabilities to class labels
predicted_classes = (predictions > 0.5).astype(int)  # Adjust the threshold as necessary
# Map 0 and 1 to 'normal' and 'abnormal'
predicted_labels = ['Anomly' if pred == 0 else 'Normal' for pred in predicted_classes.flatten()]

# Display the predictions
print("Predicted class:", predicted_labels)